base: &base
  adapter: mysql
  reconnect: false
  pool: 5
  host: localhost
  username: root
  password:
  encoding: utf8
  
development:
  <<: *base
  database: ioa_development

test:
  <<: *base
  database: ioa_test

production:
  <<: *base
  database: ioa_production
